apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-resizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-resizer
  template:
    metadata:
      labels:
        app: image-resizer
    spec:
      containers:
      - name: image-resizer
        image: image-resizer
        imagePullPolicy: Never
        ports:
        - containerPort: 5000